### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by ZeroChaos-** [tkuester/gr-reveng#4]
```
CMake Warning (dev) at /usr/lib64/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "test-reveng".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  lib/CMakeLists.txt:79 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- Found SWIG: /usr/bin/swig  
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2")
-- Found PythonInterp: /usr/bin/python (found suitable version "3.6.5", minimum required is "2") 
  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at /usr/lib64/cmake/gnuradio/GrPython.cmake:113 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  python/CMakeLists.txt:23 (include)


Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Warning (dev) at /usr/lib64/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "gnuradio-reveng".
  Use the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  python/CMakeLists.txt:45 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/lib64/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "/usr/bin/python".
Call Stack (most recent call first):
  python/CMakeLists.txt:45 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/lib64/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target
  "/var/tmp/portage/net-wireless/gr-reveng-9999/work/gr-reveng-9999/python/qa_packet_deframer.py".
Call Stack (most recent call first):
  python/CMakeLists.txt:45 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at /usr/lib64/cmake/gnuradio/GrPython.cmake:113 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  apps/CMakeLists.txt:20 (include)


Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at /usr/lib64/cmake/gnuradio/GrPython.cmake:125 (add_custom_target):
  add_custom_target cannot create target "ALL" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/var/tmp/portage/net-wireless/gr-reveng-9999/work/gr-reveng-9999/python".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /usr/lib64/cmake/gnuradio/GrPython.cmake:228 (GR_UNIQUE_TARGET)
  apps/CMakeLists.txt:22 (GR_PYTHON_INSTALL)


-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -Os -march=native -mtune=native -pipe -frecord-gcc-switches
C++             -Os -march=native -mtune=native -pipe -frecord-gcc-switches
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0
Module          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0
Shared          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0

-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/net-wireless/gr-reveng-9999/work/gr-reveng-9999_build/CMakeFiles/CMakeOutput.log".
```

**Comment by tkuester** [comment]
Tim K tagged this as, "probably-should-rewrite-for-3.8", "there-goes-my-weekend", and "I-blame-Zero".

**Comment by ZeroChaos-** [comment]
This is against 3.7 though, so.... :-)

**Comment by ZeroChaos-** [comment]
Hi @tkuester , so, about rewriting for 3.8 :-)

**Comment by tkuester** [comment]
@ZeroChaos- I just finished a first-pass rewrite for gnuradio 3.8 inside maint-3.8. I really should do some more QA work, and make sure the python has been properly ported to python3. It's not ready for prime time, but you should be able to compile it and confirm that the example .grc file runs still!
